const NAME_DAYS: Record<string, string[]> = {
  '01-01': ["Mieczysława", "Konkordiusz", "Masław", "Mieczysław", "Mieszko", "Odylon"],
  '01-02': ["Izydor", "Bazyli", "Narcyz", "Makary", "Abel", "Strzeżysław"],
  '01-03': ["Piotr", "Danuta", "Genowefa", "Arleta", "Enoch", "Włościsława"],
  '01-04': ["Grzegorz", "Eugeniusz", "Aniela", "Izabela", "Tytus", "Benedykta", "Fereol", "Leonia", "Dobromir", "Rygobert"],
  '01-05': ["Symeon", "Szymon", "Edward", "Hanna", "Emiliana", "Telesfor", "Włościbor"],
  '01-06': ["Kacper", "Baltazar", "Melchior", "Andrzej", "Balcer", "Epifania", "Jędrzej", "Bolemir", "Kasper"],
  '01-07': ["Julian", "Izydor", "Kryspin", "Lucjan", "Walenty", "Chociesław"],
  '01-08': ["Seweryn", "Heladiusz", "Erhard", "Mścisław"],
  '01-09': ["Antoni", "Julian", "Marcelina", "Julianna", "Bazylisa", "Borzymir", "Bracsław", "Marcjanna"],
  '01-10': ["Jan", "Paweł", "Wilhelm", "Anna", "Krystiana", "Agaton", "Dobrosław", "Nikanor"],
  '01-11': ["Feliks", "Hilary", "Matylda", "Mechtylda", "Honorata", "Gracja", "Hortensja", "Hortensjusz", "Hygin", "Krzesimir"],
  '01-12': ["Antoni", "Benedykt", "Ernest", "Arkadiusz", "Arkady", "Stomir", "Cezaria", "Greta", "Reginald", "Reinhold", "Tycjan"],
  '01-13': ["Bogumił", "Weronika", "Bogusława", "Godfryd", "Leoncjusz", "Melania", "Bogusąd", "Remigiusz"],
  '01-14': ["Feliks", "Amadea", "Amadeusz", "Hilary", "Odo", "Krystiana", "Nina", "Radogost"],
  '01-15': ["Paweł", "Aleksander", "Izydor", "Makary", "Maur", "Dąbrówka", "Dobrawa", "Domasław", "Domosław"],
  '01-16': ["Włodzimierz", "Waleriusz", "Treweriusz"],
  '01-17': ["Jan", "Antoni", "Przemił", "Alba", "Rościsław"],
  '01-18': ["Piotr", "Małgorzata", "Zuzanna", "Bogumił", "Krystyna", "Wenerand", "Jaropełk", "Liberata", "Pryska"],
  '01-19': ["Andrzej", "Bernard", "Biernat", "Henryk", "Marta", "Mariusz", "Erwin", "Eufemia", "Sara", "Matylda", "Mechtylda"],
  '01-20': ["Sebastian", "Dobiegniew", "Dobrożyźń", "Fabian"],
  '01-21': ["Marceli", "Agnieszka", "Jarosław", "Długomił", "Epifani", "Patrokles", "Inez", "Jarosława", "Jerosława"],
  '01-22': ["Wincenty", "Anastazy", "Gaudencjusz", "Dobromysł", "Gaudenty", "Kasandra"],
  '01-23': ["Jan", "Maria", "Klemens", "Ildefons", "Rajmund", "Emerencja", "Rajmunda", "Wrocisława"],
  '01-24': ["Tymoteusz", "Rafał", "Chwalibog", "Milena", "Ksenia", "Mirogniew", "Rafaela"],
  '01-25': ["Paweł", "Apollo", "Appollon", "Artemia", "Miłosz", "Miłowit", "Tacjana", "Tatiana"],
  '01-26': ["Leon", "Leona", "Tymoteusz", "Paula", "Polikarp", "Skarbimir", "Wanda"],
  '01-27': ["Julian", "Natalis", "Ilona", "Ninomysł", "Angela", "Chryzostom", "Jan Chryzostom", "Przybysław"],
  '01-28': ["Piotr", "Julian", "Tomasz", "Agnieszka", "Augustyn", "Karol", "Olimpia", "Waleriusz", "Flawian", "Ildefons", "Roger"],
  '01-29': ["Paweł", "Bartłomiej", "Walerian", "Waleriusz", "Żelisław", "Zdzisław", "Franciszek Salezy", "Gildas"],
  '01-30': ["Feliks", "Marcin", "Gerard", "Adelajda", "Maciej", "Sebastian", "Hiacynta", "Martyna"],
  '01-31': ["Jan", "Piotr", "Marcelina", "Euzebiusz", "Marcelin", "Ludwika", "Cyrus", "Ksawery", "Marcela", "Wirgiliusz"],
  '02-01': ["Paweł", "Emil", "Brygida", "Dobrochna", "Siemirad", "Winand", "Winanda", "Żegota"],
  '02-02': ["Maria", "Joanna", "Korneliusz", "Miłosława"],
  '02-03': ["Stefan", "Ignacy", "Wawrzyniec", "Hipolit", "Maksym", "Laurencjusz", "Błażej", "Klaudyna", "Leoniusz", "Ofelia"],
  '02-04': ["Jan", "Joanna", "Andrzej", "Józef", "Mariusz", "Weronika", "Częstogoj", "Gilbert", "Izyda", "Nataniel", "Witosława"],
  '02-05': ["Agata", "Jan", "Piotr", "Paweł", "Jakub", "Izydor", "Albin", "Adelajda", "Justynian", "Strzeżysława"],
  '02-06': ["Leon", "Leona", "Antoni", "Szymon", "Dorota", "Tytus", "Bohdan", "Bohdana", "Bogdana"],
  '02-07': ["Alfons", "Ryszard", "Romeo", "Romuald", "Sulisław"],
  '02-08': ["Jan", "Piotr", "Paweł", "Ampelia", "Ampeliusz", "Gabriela", "Lucjusz", "Sebastian", "Honorat", "Salomon", "Izajasz"],
  '02-09': ["Bernard", "Biernat", "Cyryl", "Mariusz", "Nikifor", "Eryk", "Apolonia", "Eryka", "Gorzysław", "Pola", "Rajnold"],
  '02-10': ["Apollo", "Appollon", "Jacek", "Gabriel", "Jacenty", "Scholastyka", "Tomisława"],
  '02-11': ["Maria", "Adolf", "Lucjan", "Łazarz", "Bernadeta", "Dezydery", "Olgierd", "Cedmon", "Łucjusz", "Świętomira"],
  '02-12': ["Benedykt", "Julian", "Laurenty", "Aleksy", "Ampelia", "Ampeliusz", "Saturnina", "Modest", "Humbelina", "Eulalia"],
  '02-13': ["Grzegorz", "Katarzyna", "Kaja", "Radosław", "Jordan", "Kastor", "Benigna", "Humbelina", "Toligniew"],
  '02-14': ["Walenty", "Józef", "Mikołaj", "Konrad", "Cyryl", "Zenon", "Adolf", "Krystyna", "Auksencja", "Auksencjusz", "Auksenty"],
  '02-15': ["Józef", "Sewer", "Klaudiusz", "Jordan", "Zygfryd", "Zygfryda", "Faustyn", "Jowita", "Przybyrad", "Żywia", "Żywila"],
  '02-16': ["Bernard", "Biernat", "Symeon", "Daniel", "Julianna", "Danuta", "Lucyla", "Izajasz", "Weridiana", "Wirydiana"],
  '02-17': ["Franciszek", "Julian", "Izydor", "Klemens", "Łukasz", "Konstanty", "Zbigniew", "Sylwin", "Donat"],
  '02-18': ["Symeon", "Agnieszka", "Albert", "Heladiusz", "Maksym", "Sabbas", "Konstancja", "Mojżesz", "Sylwan", "Sylwana"],
  '02-19': ["Konrad", "Henryk", "Marceli", "Arnold", "Beat", "Leoncjusz", "Manswet", "Bądzisława", "Gawin"],
  '02-20': ["Leon", "Leona", "Eustachy", "Ostap", "Ludmiła", "Ludomiła", "Euchariusz", "Siestrzewit"],
  '02-21': ["Teodor", "Feliks", "Natalis", "Fortunat", "Eleonora", "Gumbert", "Henryka", "Kiejstut", "Wyszeniega"],
  '02-22': ["Piotr", "Wiktor", "Małgorzata", "Nikifor", "Konkordia", "Wrocisław"],
  '02-23': ["Piotr", "Seweryn", "Marta", "Damian", "Łazarz", "Prymian", "Florentyn", "Roma", "Romana"],
  '02-24': ["Piotr", "Marek", "Markusław", "Lucjusz", "Maciej", "Józefa", "Bogurad", "Jaśmina"],
  '02-25': ["Małgorzata", "Cezary", "Modest", "Taras", "Tarazjusz", "Konstancjusz", "Nicefor", "Romeo", "Tolisław", "Tolisława"],
  '02-26': ["Aleksander", "Denis", "Dionizy", "Bogumił", "Nestor", "Otokar", "Cezariusz", "Mirosław"],
  '02-27': ["Aleksander", "Wiktor", "Anastazja", "Auksencja", "Auksencjusz", "Auksenty", "Gabriel", "Baldomer", "Baldomera"],
  '02-28': ["Józef", "Kaja", "Makary", "Chwalibog", "Nadbor"],
  '02-29': ["August", "Roman", "Antonia", "Oswald", "Oswalda", "Dobronieg", "Dobrosidł"],
  '03-01': ["Piotr", "Joanna", "Leon", "Leona", "Antoni", "Feliks", "Józef", "Nikifor", "Antonina", "Radosław", "Herakles"],
  '03-02': ["Piotr", "Paweł", "Franciszek", "Michał", "Henryk", "Helena", "Krzysztof", "Lew", "Absalon", "Januaria", "Halszka"],
  '03-03': ["Hieronim", "Asteriusz", "Kinga", "Kunegunda", "Maryna", "Gerwin", "Gerwina", "Wierzchosława"],
  '03-04': ["Eugeniusz", "Łucja", "Leonard", "Leonarda", "Adrian", "Lucjusz", "Arkadiusz", "Arkady", "Lew", "Kazimiera", "Kazimierz"],
  '03-05': ["Jan", "Marek", "Markusław", "Adrian", "Fryderyk", "Oliwia", "Pakosław"],
  '03-06': ["Wiktor", "Agnieszka", "Eugenia", "Róża", "Jordan", "Frydolin", "Klaudian", "Koleta", "Wojsław"],
  '03-07': ["Paweł", "Tomasz", "Felicyta", "Polikarp", "Nadmir"],
  '03-08': ["Jan", "Julian", "Stefan", "Wincenty", "Beata", "Filemon", "Miligost", "Miłogost"],
  '03-09': ["Dominik", "Katarzyna", "Kaja", "Taras", "Tarazjusz", "Franciszka", "Mścisława", "Ninosław", "Prudencjusz"],
  '03-10': ["Aleksander", "Cyprian", "Marceli", "Makary", "Porfirion", "Zwnisława"],
  '03-11': ["Benedykt", "Trofim", "Konstanty", "Konstantyn", "Prokop", "Kandyd", "Sofroniusz", "Drogosława", "Rozyna"],
  '03-12': ["Grzegorz", "Bernard", "Biernat", "Blizbor", "Józefina"],
  '03-13': ["Krystyna", "Marek", "Markusław", "Ernest", "Kasjan", "Bożena", "Bratomir", "Ewa", "Roderyk", "Trzebiesław"],
  '03-14': ["Leon", "Leona", "Jakub", "Michał", "Afrodyzja", "Afrodyzjusz", "Afrodyzy", "Matylda", "Mechtylda", "Bożeciecha"],
  '03-15': ["Klemens", "Longin", "Longina", "Krzysztof", "Ludwika", "Gościmir"],
  '03-16': ["Natalis", "Cyriak", "Hilary", "Izabela", "Abraham", "Artemia", "Herbert", "Hiacynt"],
  '03-17': ["Zbigniew", "Jan", "Gertruda", "Patrycjusz", "Regina", "Gerazym", "Harasym", "Patryk", "Zbygniew", "Zbygniewa"],
  '03-18': ["Aleksander", "Cyryl", "Marta", "Narcyz", "Trofim", "Edward", "Anzelm", "Boguchwał", "Salwator"],
  '03-19': ["Marek", "Markusław", "Józef", "Bogdan", "Sybilla"],
  '03-20': ["Klaudia", "Aleksander", "Wincenty", "Klemens", "Bogusław", "Ambroży", "Anatol", "Eufemia", "Patrycjusz", "Fotyna"],
  '03-21': ["Benedykt", "Mikołaj", "Filemon", "Marzanna", "Klemencja", "Lubomira"],
  '03-22': ["Paweł", "Katarzyna", "Bogusław", "August", "Bazylisa", "Godzisław", "Kazimierz"],
  '03-23': ["Piotr", "Feliks", "Katarzyna", "Pelagia", "Zbysław", "Eberhard", "Kondrat", "Oktawian", "Pelagiusz"],
  '03-24': ["Marek", "Markusław", "Szymon", "Sewer", "Gabriel", "Sofroniusz", "Dziersława", "Dzierżysława"],
  '03-25': ["Maria", "Łucja", "Ireneusz", "Mariola", "Wieńczysław", "Dyzma", "Jozafata", "Lutomysł"],
  '03-26': ["Teodor", "Feliks", "Nikifor", "Manuel", "Emanuel", "Emanuela", "Larysa", "Manuela", "Tworzymir"],
  '03-27': ["Jan", "Benedykt", "Ernest", "Lidia", "Narzes"],
  '03-28': ["Jan", "Joanna", "Antoni", "Aniela", "Kastor", "Krzesisław"],
  '03-29': ["Marek", "Markusław", "Cyryl", "Eustachy", "Ostap", "Wiktoryn", "Wiktoria", "Czcirad"],
  '03-30': ["Jan", "Aniela", "Leonard", "Leonarda", "Amadea", "Amadeusz", "Dobromir", "Litobor", "Lutobor", "Amelia", "Częstobor"],
  '03-31': ["Joanna", "Balbina", "Beniamin", "Gwidon", "Amos", "Dobromira", "Kornelia"],
  '04-01': ["Katarzyna", "Zbigniew", "Grażyna", "Hugo", "Teodora", "Chryzant", "Tolisław", "Hugon"],
  '04-02': ["Franciszek", "Urban", "Laurencja"],
  '04-03': ["Antoni", "Jakub", "Sykstus", "Pankracy", "Ryszard", "Cieszygor"],
  '04-04': ["Benedykt", "Izydor", "Ambroży", "Bazyli", "Zdzimir"],
  '04-05': ["Wincenty", "Irena", "Borzywoj"],
  '04-06': ["Katarzyna", "Wilhelm", "Zachariasz", "Zachary", "Ireneusz", "Ada", "Adam", "Celestyn", "Zefiryn", "Zefiryna"],
  '04-07': ["Herman", "Rufin", "Donat", "Epifaniusz", "Hegezyp", "Przecław"],
  '04-08': ["Denis", "Dionizy", "August", "Cezary", "January", "Apolinary", "Radosław", "Cezaryna", "Sieciesława"],
  '04-09': ["Marceli", "Dobrosława", "Maja", "Matron", "Wadim"],
  '04-10': ["Antoni", "Marek", "Markusław", "Małgorzata", "Michał", "Henryk", "Daniel", "Magdalena", "Makary", "Pompejusz"],
  '04-11': ["Leon", "Leona", "Filip", "Herman", "Gemma", "Jaromir"],
  '04-12': ["Andrzej", "Wiktor", "Zenon", "Sabbas", "Juliusz"],
  '04-13': ["Jan", "Małgorzata", "Justyn", "Przemysław", "Długomił", "Ida", "Marcjusz", "Przemysł", "Hermenegild"],
  '04-14': ["Maria", "Justyna", "Justyn", "Trofim", "Julianna", "Walerian", "Tyburcja", "Tyburcjusz", "Tyburcy", "Berenika"],
  '04-15': ["Bazyli", "Anastazja", "Wiktoryn", "Tytus", "Abel", "Modest", "Olimpia", "Wszegniew"],
  '04-16': ["Benedykt", "Urban", "Julia", "Erwin", "Bernadeta", "Lambert", "Leonid", "Cecylian", "Charyzjusz", "Patrycy"],
  '04-17': ["Józef", "Jakub", "Stefan", "Robert", "Innocenty", "Klara", "Anicet", "Aniceta", "Izydora", "Radociech"],
  '04-18': ["Bogusław", "Bogusława", "Ryszard", "Alicja", "Apoloniusz", "Flawiusz", "Gosława", "Gościsław"],
  '04-19': ["Leon", "Leona", "Adolf", "Włodzimierz", "Adolfa", "Cieszyrad", "Konrada", "Leontyna", "Pafnucy", "Tymon", "Werner"],
  '04-20': ["Teodor", "Szymon", "Marcelina", "Agnieszka", "Czasław", "Florencjusz", "Florenty", "Jagna", "Nawoj", "Sulpicjusz"],
  '04-21': ["Feliks", "Konrad", "Apollo", "Appollon", "Żelisław", "Anzelm", "Bartosz", "Addar", "Apollina", "Drogomił"],
  '04-22': ["Leon", "Leona", "Teodor", "Kaja", "Łukasz", "Leonia", "Heliodor", "Leonid", "Gaja", "Kajus", "Soter", "Strzeżymir"],
  '04-23': ["Jerzy", "Wojciech", "Gerard", "Helena", "Gabriela", "Adalbert"],
  '04-24': ["Aleksander", "Grzegorz", "Longin", "Longina", "Aleksy", "Erwin", "Aleksja", "Egbert", "Fidelis", "Horacjusz"],
  '04-25': ["Marek", "Markusław", "Ewodia", "Ewodiusz", "Jarosław", "Kaliksta", "Kalista"],
  '04-26': ["Maria", "Marcelina", "Klaudiusz", "Mariusz", "Marcelin", "Ryszard", "Artemon", "Klet", "Marzena", "Spycimir"],
  '04-27': ["Piotr", "Andrzej", "Anastazy", "Teofil", "Felicja", "Bożebor", "Kanizjusz", "Zyta"],
  '04-28': ["Maria", "Paweł", "Joanna", "Marek", "Markusław", "Witalis", "Afrodyzja", "Afrodyzjusz", "Afrodyzy", "Waleria"],
  '04-29': ["Piotr", "Bogusław", "Augustyn", "Robert", "Antonia", "Hugo", "Paulin", "Angelina", "Rita", "Roberta", "Ryta"],
  '04-30': ["Jakub", "Katarzyna", "Kaja", "Bartłomiej", "Afrodyzja", "Afrodyzjusz", "Afrodyzy", "Marian", "Lilla", "Zofia"],
  '05-01': ["Józef", "Jakub", "Aniela", "Jeremiasz", "Jeremi", "Lubomir"],
  '05-02': ["Anatol", "Walenty", "Walter", "Atanazy", "Zoe", "Zoja", "Zygmunta", "Witomir", "Zygmunt"],
  '05-03': ["Maria", "Aleksander", "Antonina", "Alodia", "Mariola", "Wiola", "Święchna", "Świętosława"],
  '05-04': ["Monika", "Grzegorz", "Michał", "January", "Antonia", "Florian", "Paulin"],
  '05-05': ["Teodor", "Irena", "Pius", "Waldemar", "Ita", "Penelopa", "Sabrina", "Zdziebor"],
  '05-06': ["Jan", "Filip", "Benedykta", "Ewodia", "Ewodiusz", "Judyta", "Gościwit", "Jurand"],
  '05-07': ["Benedykt", "August", "Róża", "Sykstus", "Domicjan", "Domicjana", "Florian", "Ludmiła", "Sabbas", "Flawia", "Domicela"],
  '05-08': ["Piotr", "Michał", "Heladiusz", "Amat", "Stanisław", "Dezyderia", "Ilza"],
  '05-09': ["Grzegorz", "Mikołaj", "Karolina", "Beat", "Otokar", "Job"],
  '05-10': ["Jan", "Izydor", "Symeon", "Chociesław", "Wiktoryna", "Antonin", "Częstomir", "Gordian", "Gordiana"],
  '05-11': ["Franciszek", "Benedykt", "Filip", "Ignacy", "Zuzanna", "Lew", "Adalbert", "Lutogniew", "Mamert", "Mamerta", "Miranda"],
  '05-12': ["Jan", "Joanna", "Dominik", "Domicjan", "Domicjana", "Flawia", "Pankracy", "Domicela", "Epifani", "Jazon", "Nawoja"],
  '05-13': ["Piotr", "Andrzej", "Magdalena", "Natalis", "Robert", "Aron", "Ciechosław", "Gloria", "Magda", "Serwacy"],
  '05-14': ["Maciej", "Wiktor", "Ampelia", "Ampeliusz", "Bonifacy", "Jeremiasz", "Dobiesław", "Fenenna", "Koryna"],
  '05-15': ["Zofia", "Jan", "Izydor", "Atanazy", "Cecyliusz", "Dionizja", "Nadia", "Nadzieja", "Ruprecht", "Sonia", "Strzeżysław"],
  '05-16': ["Andrzej", "Szymon", "Honorat", "Jędrzej", "Wieńczysław", "Wiktorian", "Fidol", "Germeriusz", "Jan Nepomucen"],
  '05-17': ["Wiktor", "Weronika", "Antonia", "Sławomir", "Bruno", "Herakliusz", "Paschalis"],
  '05-18': ["Feliks", "Aleksander", "Kacper", "Klaudia", "Eryk", "Sandra", "Aleksandra", "Liboriusz", "Myślibor", "Wenancjusz"],
  '05-19': ["Piotr", "Mikołaj", "Kryspin", "Augustyn", "Bernarda", "Celestyn", "Iwa", "Iwo", "Iwon", "Pękosław"],
  '05-20': ["Teodor", "Bazyli", "Anastazy", "Sabbas", "Saturnina", "Wiktoria", "Asteriusz", "Bazylides", "Iwo", "Iwon", "Bernardyn"],
  '05-21': ["Jan", "Wiktor", "Tymoteusz", "Walenty", "Przecława", "Pudens", "Rycheza", "Ryksa"],
  '05-22': ["Jan", "Emil", "Helena", "Julia", "Wiesław", "Rita", "Krzesisława", "Wiesława", "Wisława"],
  '05-23': ["Jan", "Michał", "Symeon", "Emilia", "Dezyderiusz", "Dezydery", "Eufrozyna", "Iwona", "Budziwoj"],
  '05-24': ["Joanna", "Zuzanna", "Jan", "Maria", "Wincenty", "Dagmara", "Milena", "Natan", "Cieszysława", "Orion", "Tomira"],
  '05-25': ["Magda", "Leon", "Leona", "Grzegorz", "Urban", "Wenerand", "Beda", "Imisława"],
  '05-26': ["Filip", "Emil", "Paulina", "Angelika", "Ewelina", "Marianna", "Adalwin", "Adalwina", "Alwin", "Alwina", "Więcemił"],
  '05-27': ["Jan", "Izydor", "Magdalena", "Lucjan", "Juliusz", "Oliwer", "Oliwier", "Magda", "Radowit"],
  '05-28': ["Wiktor", "Ignacy", "Wilhelm", "Emil", "Augustyn", "Heladiusz", "German", "Jaromir", "Manuel", "Priam"],
  '05-29': ["Magdalena", "Maria", "Teodor", "Bogusława", "Maksymilian", "Maksymiliana", "Magda"],
  '05-30': ["Joanna", "Feliks", "Ferdynand", "Andronik", "Sulimir"],
  '05-31': ["Teodor", "Feliks", "Aniela", "Ernesta", "Ernestyna", "Kamila", "Petronela", "Petronia", "Petroniusz"],
  '06-01': ["Bernard", "Biernat", "Jakub", "Konrad", "Symeon", "Alfons", "Magdalena", "Nikodem", "Fortunat", "Świętopełk"],
  '06-02': ["Piotr", "Maria", "Mikołaj", "Eugeniusz", "Marcelin", "Trofima", "Efrem", "Erazm", "Fotyn", "Marianna", "Marzanna"],
  '06-03': ["Ferdynand", "Konstantyn", "Paula", "Cecyliusz", "Klotylda", "Laurentyn", "Leszek", "Owidia", "Owidiusz", "Tamara"],
  '06-04': ["Franciszek", "Saturnina", "Karol", "Karp", "Braturad", "Dacjusz", "Gostmił", "Niepełka"],
  '06-05': ["Bonifacy", "Waleria", "Walter", "Nikanor", "Dobrociech"],
  '06-06': ["Symeon", "Laurenty", "Paulina", "Klaudiusz", "Dominika", "Benignus", "Norbert", "Norberta", "Więcerad"],
  '06-07': ["Paweł", "Antoni", "Robert", "Anna", "Wiesław", "Jarosław", "Lukrecja", "Ada", "Ciechomir", "Hadriana", "Wisław"],
  '06-08': ["Wilhelm", "Seweryn", "Maksym", "Adriana", "Karp", "Medard", "Wyszesław"],
  '06-09': ["Pelagia", "Anna", "Ryszard", "Felicjan", "Kalmir"],
  '06-10': ["Małgorzata", "Apollo", "Appollon", "Bogumił", "Bogumiła", "Edgar", "Mauryn"],
  '06-11': ["Feliks", "Anastazy", "Radomił", "Teodozja", "Barnaba"],
  '06-12': ["Jan", "Leon", "Leona", "Bazyli", "Narcyz", "Antonina", "Kacper", "Władysław", "Władysława", "Czesław"],
  '06-13': ["Antoni", "Herman", "Lucjan", "Tobiasz", "Chociemir"],
  '06-14': ["Justyn", "Walerian", "Eliza", "Ryszard", "Bazylides", "Ninogniew"],
  '06-15': ["Bernard", "Biernat", "Edburga", "Nikifor", "Abraham", "Witold", "Angelina", "Jolanta", "Leonida", "Witołd"],
  '06-16': ["Jan", "Justyna", "Alina", "Aneta", "Benon", "Budzimir", "Cyryk", "Ludgarda"],
  '06-17': ["Franciszek", "Adolf", "Adrianna", "Hipacy", "Radomił", "Rajner", "Drogomysł", "Izaura", "Laura", "Marcjan"],
  '06-18': ["Marek", "Markusław", "Elżbieta", "Emil", "Leonia", "Paula", "Efrem", "Gerwazy"],
  '06-19': ["Julianna", "Odo", "Michalina", "Protazy", "Gerwazy", "Borzysław", "Eurydyka"],
  '06-20': ["Franciszek", "Michał", "Edburga", "Rafał", "Bogna", "Bożena", "Bratomir", "Florentyna", "Gemma", "Hektor", "Jaktor"],
  '06-21': ["Teodor", "Marta", "Rudolf", "Rudolfa", "Rudolfina", "Alicja", "Alban", "Alojza", "Alojzy", "Demetria", "Domamir"],
  '06-22': ["Paulina", "Innocenty", "Flawiusz", "Achacjusz", "Achacy", "Agenor", "Innocenta"],
  '06-23': ["Piotr", "Józef", "Bazyli", "Zenon", "Albin", "Agrypina", "Wanda"],
  '06-24': ["Jan", "Wilhelm", "Emilia", "Longin", "Longina", "Danuta"],
  '06-25': ["Wilhelm", "Łucja", "Dorota", "Antyd", "Tolisława", "Eulogiusz", "Febron", "Febronia", "Fiebrosław", "Olbracht"],
  '06-26': ["Jan", "Paweł", "Edburga", "Dawid", "Jeremiasz", "Zdziwoj"],
  '06-27': ["Joanna", "Cyryl", "Bożydar", "Władysław", "Władysława", "Włodzisław"],
  '06-28': ["Paweł", "Leon", "Leona", "Józef", "Ireneusz", "Olga", "Zbrosław"],
  '06-29': ["Piotr", "Paweł", "Benedykta", "Dalebor", "Iweta"],
  '06-30': ["Leon", "Leona", "Trofim", "Emilia", "Lucyna", "Władysław", "Władysława", "Alpinian", "Ciechosława", "Marcjalis"],
  '07-01': ["Bogusław", "Domicjan", "Domicjana", "Karolina", "Halina", "Klarysa", "Namir", "Estera", "Niegosława", "Teobald"],
  '07-02': ["Piotr", "Urban", "Bożydar", "Otto", "Juda", "Aaron", "Jagoda", "Martynian"],
  '07-03': ["Leon", "Leona", "Longin", "Longina", "Anatol", "Jacek", "Otto", "Heliodor", "Otton", "Korneli", "Miłosław"],
  '07-04': ["Teodor", "Józef", "Julian", "Elżbieta", "Alf", "Alfred", "Innocenty", "Odo", "Aurelian", "Aggeusz", "Malwina", "Odon"],
  '07-05': ["Antoni", "Jakub", "Wilhelm", "Bartłomiej", "Marta", "Trofima", "Filomena", "Zoe", "Zoja", "Przybywoj"],
  '07-06': ["Dominik", "Łucja", "Zuzanna", "Agrypina", "Dominika", "Chociebor", "Gotard", "Ignacja", "Nazaria", "Niegosław"],
  '07-07': ["Piotr", "Antoni", "Benedykt", "Cyryl", "Pompejusz", "Wilibald", "Kira", "Metody", "Sędzisława"],
  '07-08': ["Eugeniusz", "Elżbieta", "Adrian", "Prokop", "Edgar", "Chwalimir", "Kilian", "Kiliana", "Odeta", "Wirginia"],
  '07-09': ["Joanna", "Mikołaj", "Łucja", "Zenon", "Róża", "Weronika", "Patrycjusz", "Anatola", "Anatolia", "Lucja", "Sylwia"],
  '07-10': ["Aleksander", "Filip", "Aniela", "January", "Witalis", "Zacheusz", "Samson", "Sylwan", "Witołd", "Amalberga", "Rufina"],
  '07-11': ["Benedykt", "Cyprian", "Pelagia", "Karina", "Olga", "Oliwer", "Oliwier", "Pius", "Placyd", "Kalina", "Sawin", "Siepraw"],
  '07-12': ["Piotr", "Paweł", "Leon", "Leona", "Feliks", "Andrzej", "Henryk", "Weronika", "Euzebiusz", "Epifania", "Gwalbert"],
  '07-13': ["Jakub", "Małgorzata", "Eugeniusz", "Justyna", "Ernest", "Sara", "Trofima", "Radomiła", "Joel"],
  '07-14': ["Franciszek", "Marceli", "Marcelina", "Damian", "Izabela", "Marcelin", "Kamil", "Kosma", "Bonawentura", "Dobrogost"],
  '07-15': ["Ignacy", "Henryk", "Daniel", "Włodzimierz", "Dawid", "Egon", "Lubomysł", "Niecisław", "Roksana"],
  '07-16': ["Andrzej", "Benedykt", "Stefan", "Eustachy", "Ostap", "Faust", "Dziersław", "Dzierżysław", "Marika"],
  '07-17': ["Leon", "Leona", "Aleksander", "Andrzej", "Marceli", "Marcelina", "Aleksy", "Bogdan", "Karolina", "Aleksja", "Konstancja"],
  '07-18': ["Szymon", "Robert", "Erwin", "Arnold", "Kamil", "Materna", "Maternus", "Teodozja", "Unisław", "Wespazjan"],
  '07-19': ["Wincenty", "Marcin", "Alf", "Alfred", "Rufin", "Arseniusz", "Litobor", "Lutobor", "Wodzisław"],
  '07-20': ["Paweł", "Leon", "Leona", "Małgorzata", "Hieronim", "Ludwika", "Czesław", "Czesława", "Eliasz", "Heliasz"],
  '07-21': ["Andrzej", "Wiktor", "Benedykt", "Ignacy", "Daniel", "Paulina", "Prokop", "Prakseda", "Stojsław"],
  '07-22': ["Albin", "Magdalena", "Wawrzyniec", "Laurencjusz", "Pankracy", "Bolesława", "Magda"],
  '07-23': ["Joanna", "Apolinary", "Żelisław", "Bogna", "Apolinaria"],
  '07-24': ["Antoni", "Krystyna", "Krystiana", "Olga", "Kinga", "Kunegunda", "Wojciecha"],
  '07-25': ["Krzysztof", "Jakub", "Alfons", "Rudolf", "Rudolfa", "Rudolfina", "Olimpia", "Walentyna", "Nieznamir", "Sławosz"],
  '07-26': ["Anna", "Anita", "Grażyna", "Hanna", "Bartłomieja", "Mirosława"],
  '07-27': ["Julia", "Laurenty", "Magdalena", "Aureli", "Lilla", "Natalia", "Natasza", "Pantaleon", "Lilia", "Magda", "Wszebor"],
  '07-28': ["Wiktor", "Innocenty", "Alfonsa", "Alfonsyna", "Marcela", "Pantaleon", "Samson", "Świętomir"],
  '07-29': ["Marta", "Maria", "Urban", "Konstantyn", "Lucyla", "Faustyn", "Beatrycze", "Cierpisław", "Olaf", "Serafina"],
  '07-30': ["Julia", "Ludmiła", "Maryna", "Abdon", "Julita", "Ubysław", "Ubysława", "Zdobysław"],
  '07-31': ["Ignacy", "Justyn", "Helena", "Emilian", "Beat", "Alfonsa", "Alfonsyna", "Ernesta", "Ludomir", "Demokryt"],
  '08-01': ["Piotr", "Konrad", "Alfons", "Justyn", "Rudolf", "Rudolfa", "Rudolfina", "Nadia", "Nadzieja", "Brodzisław"],
  '08-02': ["Maria", "Stefan", "Karina", "Gustaw", "Gustawa", "Borzysława"],
  '08-03': ["Symeon", "Nikodem", "Lidia", "Szczepan"],
  '08-04': ["Maria", "Dominik", "Alf", "Alfred", "Protazy", "Arystarch", "Mironieg"],
  '08-05': ["Maria", "Cyriak", "Abel", "Oswald", "Oswalda", "Memiusz", "Nonna", "Stanisława"],
  '08-06': ["Jakub", "Stefan", "Wincenty", "January", "Namir", "Felicysym"],
  '08-07': ["Konrad", "Sykstus", "Albert", "Dorota", "Klaudia", "Andromeda", "Dobiemir", "Doryda", "Kajetan", "Licynia"],
  '08-08': ["Joanna", "Dominik", "Cyryl", "Cyprian", "Emilian", "Cyriak", "Niezamysł", "Sylwiusz"],
  '08-09': ["Jan", "Roman", "Domicjan", "Domicjana", "Edyta", "Klarysa", "Romuald", "Miłorad", "Roland"],
  '08-10': ["Bernard", "Biernat", "Bożydar", "Wawrzyniec", "Amadea", "Amadeusz", "Bogdan", "Filomena", "Asteria", "Borys"],
  '08-11': ["Aleksander", "Zuzanna", "Herman", "Włodzimierz", "Lukrecja", "Tyburcja", "Tyburcjusz", "Tyburcy", "Ligia"],
  '08-12': ["Piotr", "Klara", "Fotyn", "Leonida", "Bądzisław", "Hilaria", "Lech"],
  '08-13': ["Jan", "Helena", "Hipolit", "Gertruda", "Kasjan", "Adriana", "Radomiła", "Diana", "Hipolita", "Wojbor"],
  '08-14': ["Alf", "Alfred", "Euzebiusz", "Maksymilian", "Maksymiliana", "Atanazja", "Kalikst", "Dobrowoj", "Dobrowoja"],
  '08-15': ["Maria", "Napoleon"],
  '08-16': ["Stefan", "Emil", "Ambroży", "Joachim", "Domarad", "Roch"],
  '08-17': ["Joanna", "Anastazja", "Julianna", "Jacek", "Anita", "Eliza", "Liberat", "Miron", "Bertram", "Jaczewoj", "Zawisza"],
  '08-18': ["Helena", "Bogusława", "Bronisław", "Klara", "Ilona", "Nela", "Agapit", "Tworzysława"],
  '08-19': ["Jan", "Piotr", "Julian", "Emilia", "Sykstus", "Juliusz", "Ludwik", "Bolesław", "Sebald"],
  '08-20': ["Jan", "Bernard", "Biernat", "Sara", "Sabin", "Sobiesław", "Samuel", "Samuela", "Sieciech"],
  '08-21': ["Joanna", "Franciszek", "Bernard", "Biernat", "Adolf", "Emilian", "Filipina", "Męcimir"],
  '08-22': ["Maria", "Cezary", "Tymoteusz", "Hipolit", "Zygfryd", "Zygfryda", "Dalegor", "Fabrycjan", "Fabrycy", "Namysław"],
  '08-23': ["Filip", "Laurenty", "Róża", "Walerian", "Apolinary", "Zacheusz", "Benicjusz", "Sulirad"],
  '08-24': ["Joanna", "Bartłomiej", "Anita", "Michalina", "Bartosz", "Halina", "Jerzy", "Cieszymir", "Malina"],
  '08-25': ["Grzegorz", "Michał", "Ludwik", "Elwira", "Gaudencjusz", "Kalasanty", "Luiza", "Sieciesław"],
  '08-26': ["Maria", "Joanna", "Konstanty", "Maksym", "Sandra", "Wiktorian", "Zefiryn", "Zefiryna", "Dobroniega"],
  '08-27': ["Teodor", "Józef", "Małgorzata", "Cezary", "Amadea", "Amadeusz", "Adrianna", "Rufus", "Monika", "Gebhard"],
  '08-28': ["Aleksander", "Alfons", "Augustyn", "Aleksy", "Sobiesław", "Adelina", "Joachima", "Patrycja", "Stronisław"],
  '08-29': ["Jan", "Sabina", "Flora", "Mederyk", "Mederyka", "Racibor"],
  '08-30': ["Tekla", "Miron", "Adaukt", "Częstowoj", "Gaudencja", "Rebeka"],
  '08-31': ["Paulina", "Amat", "Bohdan", "Prymian", "Rajmund", "Albertyna", "Ramona", "Świętosław"],
  '09-01': ["August", "Sykstus", "Bronisław", "Bronisława", "Idzi", "Ruta"],
  '09-02': ["Denis", "Dionizy", "Julian", "Stefan", "Wilhelm", "Henryk", "Bohdan", "Eliza", "Tobiasz", "Absalon", "Dziesław"],
  '09-03': ["Jan", "Antoni", "Wincenty", "Szymon", "Bartłomiej", "Zenon", "Natalis", "Bronisław", "Eufemia", "Izabela"],
  '09-04': ["Ida", "Rozalia", "Agatonik", "Daniela", "Hermiona", "Lilianna", "Rościgniew"],
  '09-05': ["Justyna", "Wawrzyniec", "Dorota", "Fereol", "Herakles", "Herkulan", "Herkules", "Stronisława"],
  '09-06': ["Michał", "Eugeniusz", "Albin", "Eugenia", "Zachariasz", "Zachary", "Aleksja", "Beata", "Magnus", "Uniewit"],
  '09-07': ["Melchior", "Regina", "Ryszard", "Domasława", "Sozont"],
  '09-08': ["Maria", "Radosław", "Adrianna", "Nestor", "Wiola", "Radosława"],
  '09-09': ["Piotr", "Denis", "Dionizy", "Aureliusz", "Grażyna", "Audomar", "Otmar", "Edeltrauda", "Gorgoniusz", "Ożanna"],
  '09-10': ["Leon", "Leona", "Mikołaj", "Klemens", "Łukasz", "Aldona", "Mścibor", "Nimfodora", "Pulcheria"],
  '09-11': ["Jan", "Feliks", "Jacek", "Prot", "Ścibor", "Dagna", "Naczęsław"],
  '09-12': ["Piotr", "Maria", "Sylwin", "Cyrus", "Gwidon", "Radzimir"],
  '09-13': ["Aleksander", "Filip", "Eugenia", "Amat", "Aureliusz", "Morzysław"],
  '09-14': ["Bernard", "Biernat", "Szymon", "Cyprian", "Materna", "Maternus", "Siemomysł"],
  '09-15': ["Maria", "Kaja", "Albin", "Nikodem", "Budzigniew"],
  '09-16': ["Franciszek", "Wiktor", "Łucja", "Cyprian", "Eugenia", "Eufemia", "Edyta", "Antym", "Edda", "Jakobina", "Jakubina"],
  '09-17': ["Franciszek", "Justyna", "Justyn", "Narcyz", "Teodora", "Dezyderiusz", "Lambert", "Zygmunta", "Ariadna"],
  '09-18': ["Józef", "Irena", "Tytus", "Zachariasz", "Zachary", "Fereol", "Balcer", "Baltazar", "Zofia", "Dobrowit", "Ryszarda"],
  '09-19': ["Teodor", "Alfons", "Zuzanna", "Marta", "Trofim", "January", "Konstancja", "Festus", "Sydonia", "Więcemir"],
  '09-20': ["Denis", "Dionizy", "Klemens", "Eustachy", "Irena", "Ostap", "Filipina", "Mieczysława", "Eustachiusz", "Fausta"],
  '09-21': ["Marek", "Markusław", "Laurenty", "Hipolit", "Kastor", "Jonasz", "Bernardyna", "Bożeciech", "Ifigenia", "Mateusz"],
  '09-22': ["Ignacy", "Tomasz", "Joachim", "Daria", "Maurycy", "Prosimir"],
  '09-23': ["Bogusław", "Tekla", "Boguchwała", "Libert", "Linus", "Liwiusz"],
  '09-24': ["Maria", "Teodor", "Gerard", "Tomir", "Uniegost"],
  '09-25': ["Piotr", "Franciszek", "Wincenty", "Aurelia", "Kamil", "Rufus", "Władysław", "Władysława", "Aureli", "Aurelian"],
  '09-26': ["Justyna", "Cyprian", "Euzebiusz", "Łękomir"],
  '09-27': ["Urban", "Damian", "Kosma", "Przedbor"],
  '09-28': ["Jan", "Marek", "Markusław", "Wawrzyniec", "Laurencjusz", "Salomon", "Sylwin", "Wacław", "Wacława", "Amalia"],
  '09-29': ["Michał", "Franciszek", "Rafał", "Michalina", "Dadzbog", "Dadzboga"],
  '09-30': ["Wiktor", "Grzegorz", "Hieronim", "Felicja", "Sonia", "Zofia", "Honoriusz", "Imisław", "Wiara"],
  '10-01': ["Jan", "Danuta", "Benigna", "Igor", "Cieszysław", "Remigiusz"],
  '10-02': ["Denis", "Dionizy", "Teofil", "Leodegar", "Stanimir"],
  '10-03': ["Eustachy", "Gerard", "Heliodor", "Józefa", "Kandyd", "Teresa", "Ewald", "Ewalda", "Sierosław"],
  '10-04': ["Franciszek", "Konrad", "Rozalia", "Manfred", "Manfreda"],
  '10-05': ["Justyn", "Apolinary", "Flawia", "Faust", "Igor", "Konstancjusz", "Placyd", "Charytyna", "Konstans"],
  '10-06': ["Roman", "Bronisław", "Brunon", "Artur", "Alberta", "Fryderyka"],
  '10-07': ["Maria", "Marek", "Markusław", "Stefan", "Justyna", "August", "Tekla", "Rościsława"],
  '10-08': ["Symeon", "Marcin", "Pelagia", "Ewodia", "Ewodiusz", "Artemon", "Brygida", "Laurencja", "Marcjusz", "Demetriusz"],
  '10-09': ["Jan", "Denis", "Dionizy", "Bożydar", "Bogdan", "Sara", "Arnold", "Ludwik", "Atanazja", "Dionizjusz"],
  '10-10': ["Leon", "Leona", "Franciszek", "Zbigniew", "Paulin", "Przemysław", "German", "Kalistrat", "Lutomir", "Tomił"],
  '10-11': ["Maria", "Emilian", "Brunon", "Marian", "Aldona", "Burchard", "Dobromiła", "Germanik", "Placyda"],
  '10-12': ["Eustachy", "Ostap", "Cyriak", "Maksymilian", "Maksymiliana", "Witold", "Serafin", "Edwin", "Grzymisław"],
  '10-13': ["Mikołaj", "Daniel", "Magdalena", "Teofil", "Edward", "Gerald", "Maurycy", "Wacław", "Wacława", "Geraldyna"],
  '10-14': ["Bernard", "Biernat", "Dominik", "Fortunata", "Kalikst", "Alan", "Dzierżymir"],
  '10-15': ["Sewer", "Tekla", "Brunon", "Teresa", "Gościsława", "Jadwiga"],
  '10-16': ["Grzegorz", "Denis", "Dionizy", "Emil", "Ambroży", "Gerard", "Aurelia", "Florentyna", "Gaweł", "Iga"],
  '10-17': ["Wiktor", "Małgorzata", "Ignacy", "Zuzanna", "Rudolf", "Rudolfa", "Rudolfina", "Lucyna", "Marian", "Augustyna"],
  '10-18': ["Julian", "Łukasz", "Hanna", "Remigiusz"],
  '10-19': ["Piotr", "Paweł", "Pelagia", "Ferdynand", "Skarbimir", "Ziemowit", "Kleopatra", "Siemowit"],
  '10-20': ["Apollo", "Appollon", "Irena", "Witalis", "Budzisława", "Jan Kanty", "Wendelin"],
  '10-21': ["Bernard", "Biernat", "Elżbieta", "Pelagia", "Hilary", "Klementyna", "Celina", "Dobromił", "Nunila"],
  '10-22': ["Marek", "Markusław", "Filip", "Sewer", "Alodia", "Abercjusz", "Kordian", "Kordula", "Przybysława"],
  '10-23': ["Jan", "Teodor", "Ignacy", "Seweryn", "Roman", "Giedymin", "Marlena", "Odila", "Świętochna", "Włościsław"],
  '10-24': ["Antoni", "Marek", "Markusław", "Filip", "Marcin", "Rafał", "Salomon", "Boleczest", "Pamfilia"],
  '10-25': ["Kryspin", "Bonifacy", "Maur", "Taras", "Tarazjusz", "Chryzant", "Daria", "Walentyna", "Inga", "Sambor"],
  '10-26': ["Ludmiła", "Lucyna", "Ewaryst", "Lutosław", "Łucjan", "Łucjana"],
  '10-27': ["Wincenty", "Sabina", "Iwona", "Frumencjusz", "Siestrzemił"],
  '10-28': ["Szymon", "Juda", "Tadeusz", "Wszeciech"],
  '10-29': ["Franciszek", "Teodor", "Narcyz", "Euzebia", "Lubogost", "Wioleta"],
  '10-30': ["Klaudiusz", "Edmund", "Przemysław", "Zenobia"],
  '10-31': ["Antoni", "Alfons", "Urban", "Łukasz", "Narcyz", "Antonina", "Lucyla", "Saturnin", "Augusta", "Godzimir"],
  '11-01': ["Andrzej", "Seweryn", "Konradyn", "Wiktoryna", "Nikola", "Warcisław"],
  '11-02': ["Małgorzata", "Ambroży", "Wiktoryn", "Tobiasz", "Bohdana", "Stomir", "Eudoksjusz"],
  '11-03': ["Cezary", "Bogumił", "Sylwia", "Chwalisław", "Hubert", "Huberta"],
  '11-04': ["Witalis", "Karol", "Mojżesz", "Olgierd", "Dżesika", "Emeryk", "Emeryka", "Karol Boromeusz", "Modesta"],
  '11-05': ["Marek", "Markusław", "Elżbieta", "Florian", "Trofima", "Zachariasz", "Zachary", "Sławomir", "Blandyn"],
  '11-06': ["Feliks", "Leonard", "Leonarda", "Gabriela", "Ziemowit", "Trzebowit"],
  '11-07': ["Antoni", "Longin", "Longina", "Karina", "Melchior", "Florentyn", "Przemił", "Achilles", "Amaranta", "Engelbert"],
  '11-08': ["Wiktor", "Seweryn", "Sewer", "Bożydar", "Klaudiusz", "Wiktoryn", "Adrian", "Wiktoria", "Godfryd", "Hadrian"],
  '11-09': ["Joanna", "Teodor", "Nestor", "Teodora", "Genowefa", "Bogudar", "Ursyn"],
  '11-10': ["Leon", "Leona", "Andrzej", "Stefan", "Ludomir", "Nela", "Lena", "Nimfa", "Probus"],
  '11-11': ["Marcin", "Teodor", "Bartłomiej", "Anastazja", "Jozafat", "Maciej", "Prot", "Spycisław"],
  '11-12': ["Marcin", "Jozafat", "Witold", "Jonasz", "Konradyn", "Cibor", "Czcibor", "Izaak", "Konradyna", "Krystyn", "Renat"],
  '11-13': ["Jan", "Mikołaj", "Eugeniusz", "Arkadiusz", "Arkady", "Augustyna", "Stanisław", "Brykcjusz", "Liwia", "Walentyn"],
  '11-14': ["Józef", "Elżbieta", "Laurenty", "Damian", "Agata", "Judyta", "Kosma", "Antyd", "Hipacy", "Serafin", "Ścibor"],
  '11-15': ["Alfons", "Albert", "Artur", "Roger", "Idalia", "Leopold", "Leopoldyna", "Przybygniew"],
  '11-16': ["Piotr", "Maria", "Paweł", "Denis", "Dionizy", "Małgorzata", "Edmund", "Aureliusz", "Gertruda", "Audomar", "Otmar"],
  '11-17': ["Grzegorz", "Denis", "Dionizy", "Jozafat", "Hugo", "Zacheusz", "Zbysław", "Floryn", "Sulibor"],
  '11-18': ["Aniela", "Tomasz", "Leonard", "Leonarda", "Roman", "Gabriela", "Karolina", "Odo", "Filipina", "Otto", "Otton"],
  '11-19': ["Paweł", "Elżbieta", "Seweryn", "Kryspin", "Mironiega", "Salome", "Salomea"],
  '11-20': ["Feliks", "Ampelia", "Ampeliusz", "Anatol", "Edmund", "Narzes", "Jeron", "Maksencja", "Oktawia", "Oktawiusz"],
  '11-21': ["Piotr", "Maria", "Konrad", "Albert", "Wiesław", "Regina", "Rufus", "Elwira", "Janusz", "Twardosław"],
  '11-22': ["Marek", "Markusław", "Maur", "Cecylia", "Wszemiła"],
  '11-23': ["Klemens", "Lukrecja", "Adela", "Felicyta", "Fotyna", "Erast", "Orestes", "Przedwoj"],
  '11-24': ["Jan", "Franciszek", "Gerard", "Emilia", "Protazy", "Dobrosław", "Emma", "Flora", "Biruta", "Ema", "Gerarda"],
  '11-25': ["Katarzyna", "Kaja", "Erazm", "Tęgomir"],
  '11-26': ["Jan", "Konrad", "Leonard", "Leonarda", "Sylwester", "Delfin", "Dobiemiest", "Lechosław", "Lechosława"],
  '11-27': ["Dominik", "Jozafat", "Maksymilian", "Maksymiliana", "Zygfryd", "Zygfryda", "Damazy", "Gustaw", "Gustawa"],
  '11-28': ["Grzegorz", "Jakub", "Rufin", "Zdzisław", "Gościrad", "Lesław", "Lesława"],
  '11-29': ["Walter", "Błażej", "Fryderyk", "Klementyna", "Paramon", "Przemysł", "Saturnin", "Bolemysł"],
  '11-30': ["Andrzej", "Justyna", "Konstanty", "Maura", "Zbysława"],
  '12-01': ["Edmund", "Gosława", "Iwa", "Natalia", "Natasza", "Eligia", "Eligiusz", "Platon", "Sobiesława"],
  '12-02': ["Paulina", "Wiktoryn", "Aurelia", "Balbina", "Budzisława", "Sulisław", "Bibiana", "Blanka", "Ludwina", "Sylweriusz"],
  '12-03': ["Franciszek", "Kryspin", "Lucjusz", "Kasjan", "Ksawery", "Unimir"],
  '12-04': ["Barbara", "Piotr", "Klemens", "Hieronim", "Chrystian", "Krystian"],
  '12-05': ["Kryspin", "Anastazy", "Krystyna", "Edyta", "Sabina", "Gerald", "Kryspina", "Pęcisława"],
  '12-06': ["Mikołaj", "Emilian", "Agata", "Angelika", "Dionizja", "Jarema"],
  '12-07': ["Marcin", "Ambroży", "Agaton", "Ninomysł"],
  '12-08': ["Maria", "Apollo", "Appollon", "Boguwola", "Narcyza", "Wirginiusz"],
  '12-09': ["Joachim", "Wiesław", "Waleria", "Delfina", "Leokadia", "Wielisława"],
  '12-10': ["Maria", "Andrzej", "Julia", "Judyta", "Nikoleta", "Polidor", "Radzisława"],
  '12-11': ["Stefan", "Daniel", "Julia", "Damazy", "Waldemar", "Wojmir"],
  '12-12': ["Joanna", "Aleksander", "Edburga", "Adelajda", "Dagmara", "Paramon"],
  '12-13': ["Łucja", "Edburga", "Róża", "Auksencja", "Auksencjusz", "Auksenty", "Bernarda", "Jodok", "Otylia", "Włodzisława"],
  '12-14': ["Izydor", "Alf", "Alfred", "Pompejusz", "Arseniusz", "Spirydion", "Nahum", "Naum", "Noemi", "Sławobor"],
  '12-15': ["Walerian", "Cecylia", "Fortunata", "Mścigniew", "Mścigniewa", "Wolimir"],
  '12-16': ["Adelajda", "Alina", "Albina", "Ananiasz", "Zdzisława"],
  '12-17': ["Łukasz", "Florian", "Łazarz", "Jolanta", "Żerosław", "Żyrosław"],
  '12-18': ["Bogusław", "Auksencja", "Auksencjusz", "Auksenty", "Wilibald", "Arkadia", "Wszemir"],
  '12-19': ["Urban", "Tymoteusz", "Abraham", "Beniamin", "Kazimiera", "Dariusz", "Nemezjusz"],
  '12-20': ["Dominik", "Dagmara", "Teofil", "Bogumiła", "Liberat", "Amon"],
  '12-21': ["Tomasz", "Honorat", "Festus", "Balbin", "Temistokles", "Tomisław"],
  '12-22': ["Zenon", "Beata", "Flawian", "Franciszka", "Honorata", "Drogomir", "Gryzelda", "Ksawera", "Ksaweryna"],
  '12-23': ["Wiktoria", "Sławomir", "Anatola", "Anatolia", "Dagobert", "Sławomira"],
  '12-24': ["Adam", "Ewa", "Grzegorz", "Adela", "Ewelina", "Irmina", "Adamina", "Druzjan", "Druzjanna", "Godzisława"],
  '12-25': ["Piotr", "Anastazja", "Eugenia", "Natan", "Spirydion"],
  '12-26': ["Denis", "Dionizy", "Szczepan", "Wrociwoj"],
  '12-27': ["Jan", "Cezary", "Fabia", "Fabiola", "Radomysł", "Żaneta"],
  '12-28': ["Antoni", "Emma", "Godzisław", "Dobrowieść", "Teofila"],
  '12-29': ["Dominik", "Marcin", "Tomasz", "Trofim", "Dawid", "Prymian", "Gosław", "Jonatan"],
  '12-30': ["Denis", "Dionizy", "Katarzyna", "Eugeniusz", "Sewer", "Łazarz", "Irmina", "Rajner", "Sabin", "Anizja", "Dawida"],
  '12-31': ["Sylwester", "Kaja", "Mariusz", "Saturnina", "Sebastian", "Donata", "Korneliusz", "Melania", "Tworzysław"],
};

const MONTHS = [
  'stycznia',
  'lutego',
  'marca',
  'kwietnia',
  'maja',
  'czerwca',
  'lipca',
  'sierpnia',
  'września',
  'października',
  'listopada',
  'grudnia',
];

export function getNameDaysForDate(date: Date) {
  const month = date.getMonth() + 1;
  const day = date.getDate();
  const key = `${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;

  return {
    label: `${day} ${MONTHS[month - 1]}`,
    names: NAME_DAYS[key] ?? ['Dziś sprawdź lokalny kalendarz imienin'],
  };
}
